question/urls.py
from django.urls import path
from . import views

app_name="question"
urlpatterns = [
    path('', views.questionIndex, name="home" ),
    path("result", views.finalResult, name="finalResult")
]

story/urls.py
from django.urls import path
from .views import StoryDetail, StoryList
from . import views 

app_name = 'story'
urlpatterns = [

    path('', views.index, name="index" ),
    path('<int:id>/detail', views.storyDetail, name="detail")
]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('story.urls', namespace='story')),
    path('story-index/', include('question.urls', namespace='question'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

question/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question = models.CharField(max_length=200)
    order = models.IntegerField(default=0)
    label = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'
        ordering = ('-question',)
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField(max_length=200)
    choice_text = models.CharField(max_length=200)
    is_correct= models.BooleanField(default=False)

    def __str__(self):
        return self.choice
    
    class Meta:
        verbose_name = 'Choice'
        verbose_name_plural = "Choice"

story/models.py
from django.db import models
from django.shortcuts import reverse

class Story(models.Model):
	title = models.CharField(max_length = 250)
	slug = models.SlugField(max_length = 250)
	body = models.TextField()
	created= models.DateField(auto_now=True)

	class Meta:
		verbose_name = 'Story'
		verbose_name_plural = 'Stories'
		ordering = ('-created', 'title',)
	
	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse("story:detail", args=[self.id])
	

question/views.py
import os
import time
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Question, Choice

# Create your views here.

def questionIndex(request):
    questions = Question.objects.order_by('-created')[:10]
    request.session['questions_ids'] = [question.id for question in questions]
    context = {'questions': questions}
    return render(request, 'question/forms.html', context )



def finalResult(request):
    questions = Question.objects.filter(id__in=request.session['questions_ids']).prefetch_related('choice_set')
    number_of_correct_answers = 0
    
    for question in questions:
        form_choice_name = 'choice_{}'.format(question.id)
        user_answer = request.POST.get(form_choice_name, '')

        if not user_answer:
            continue

        for choice in question.choice_set.all():
            if choice.choice_text == user_answer:
                if choice.is_correct:
                    number_of_correct_answers += 1          
                break
            
    scores = number_of_correct_answers *5
    total_scores = scores * 10
    int_scores = scores / total_scores
    percentage_scores = 100 * (scores / 50)
    if percentage_scores >= 75:
        grade = 'congrats, you passed'
    else:
        grade = 'oh!! no, try again'

    context_data = {
        'number_of_correct_answers': number_of_correct_answers,
        'scores': scores,
        'percentage_scores': percentage_scores,
        'grade': grade
    }

    return render(request, 'question/result.html', context_data)

story/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Story

class StoryList(ListView):
    model = Story
    context_object_name = 'stories'
    template_name='story/index.html'

def index(request):
    stories = Story.objects.all()
    return render(request, 'story/index.html', {'stories':stories})

def storyDetail(request, id):
    story = get_object_or_404(Story, id=id)
    return render(request, 
            'story/detail.html', 
            {'story':story})


class StoryDetail(DetailView):
    model = Story
    template_name='story/detail.html'

templates/base.html
{% load static %}
<html>
  <!DOCYYPE html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}" >
    <script src="{% static 'js/timer.js' %}" defer></script>
    <title></title>
    <meta charset="utf-8">
  </head>
    <nav>
      <div class="mytitle">
        My Quizz App
      </div>
    </nav> 
  {% block content %}

  {% endblock content %}
</html>

templates/question/forms.html
{% extends 'base.html' %}
{% load static %}
<div class="form-detail">
  {% block content %}
    <div class="test-timer">
      <span><p>your time expires in:</></span>
      <h2 id="timer">
      </h2>
    </div>
    <form method="post" id="quizzForm" action="{% url 'question:finalResult' %}">
      
      {% csrf_token %}
      <ul>
        {% for question  in questions  %}
          <li>
         
            {% if question %}
              <p>{{question.label}}</p>
              {% for c in question.choice_set.all  %}<br>
                <input type="radio" name="choice_{{ question.id }}" id="choice{{forloop.counter}}" value="{{c.choice_text}}">
                <label for="choice{{questtion.forloop.counter}}">{{c.choice_text}}</label>
              {% endfor %}      
            {% endif %}
          </li>
        {% endfor %}
      <ul>
      <button id="url" type="submit">submit</button>
    </form>
  {% endblock content %}

</div>

templates/question/index.html
{% extends 'base.html' %}

templates/question/result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="detail">
		<div class="header">  
 	   <h2>Welcome !!!</h2>
		</div>
		<div class="result">
			<h3>Below is the detail of ur quizz</h3>
			<span class="">
				<h4>your Scored: </h4><p>{{scores}}</p>
				<h4>percentage scores:  </h4><p>{{percentage_scores}}</p>
				<h4>Grade:</h4><p>{{grade}}</p>

			</span>
		</div>
	</div>

{% endblock content %}

templates/story/detail.html
<!DOCTYPE html>
<html>
  {% extends 'base.html' %}
  <head>
    <title>Article Detail Page</title>
    <meta charset="utf-8"> 
  </head> 
    {% block content %}
      <div class="title">
        <h1>{{story.title}}</h1>
      </div>
      <div class="description">
        <p>{{story.body}}</p>
      </div>
      <div class="button">
        <a href="{% url 'question:home' %}" >take Quizz</a>
      </div>
    {% endblock content %}
 
  
</html>

templates/story/index.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}
  {% block content %}
    <div class="instruction">
      <h1>Welcome</h1><br>
      <h3>Kindly go through these basic guideline on how to proceed with your quizz</h3>
      <ul>
        <li>Read the article carefully and answer the questions that follows </li>
        <li>Each question carrys 5 marks each</li>
        <li>You will have 7minutes to answer all these questions after which the quizz will be submited</li>
        <li>they pass mark for the quizz is 75%</li>
      </ul>
    </div>
    <div class="title">
      {% for story in stories  %}
        <p>kindly click on the link below to proceed </p> <h3> <a href="{{story.get_absolute_url}}">{{story.title}}</a></h3>
      {% endfor %}
    </div>
  {% endblock content %}
</html>